@BaseApiUrl = http://localhost:6080

GET {{BaseApiUrl}}

### User Login
GET {{BaseApiUrl}}/user/login

POST {{BaseApiUrl}}/user/login
Content-Type: application/json

{  
    "username": "haivop",
    "password": "pass123"
}

### User Login
GET {{BaseApiUrl}}/user/signup

POST {{BaseApiUrl}}/user/signup
Content-Type: application/json

{  
    "username": "haivop", 
    "email": "example.box@gmail.com",
    "password": "pass123"
}

### User Account
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJiM2FmYTU4LWJlZTEtMTFmMC04Y2Y3LTAyNTBlZGMxMTFjNSIsInVzZXJuYW1lIjoiaGFpdm9wIiwiZW1haWwiOiJleGFtcGxlLmJveEBnbWFpbC5jb20iLCJpYXQiOjE3NjI5NDIyMDYsImV4cCI6MTc2Mjk0NTgwNn0.zZJw-foBYOc4g3GcVhRyKRQ1dc7WdBsClGvsDdqH8sg

GET {{BaseApiUrl}}/user/account
Authorization: Bearer {{token}}

### World Create

GET {{BaseApiUrl}}/world/create

POST {{BaseApiUrl}}/world/create
Content-Type: application/json
Authorization: Bearer {{token}}

{  
    "title": "TestWorld1", 
    "description": "world for test",
    "is_public": "1",
    "map_url": "",
    "coAuthors": {}
}

### World Page

@world_id = 74402d7f-befc-11f0-8cf7-0250edc111c5

GET {{BaseApiUrl}}/world/{{world_id}}

### World Update

GET {{BaseApiUrl}}/world/{{world_id}}/edit

PATCH {{BaseApiUrl}}/world/{{world_id}}
Content-Type: application/json

{
    "title": "MystriaWorld", 
    "description": "world for test",
    "is_public": "1",
    "map_url": "",
    "coAuthors": {}
}

### World Delete 

DELETE {{BaseApiUrl}}/world/{{world_id}}

### WorldItem Artifact Create

GET {{BaseApiUrl}}/world/{{world_id}}/artifact/create

POST {{BaseApiUrl}}/world/{{world_id}}/artifact/create
Content-Type: application/json

{  
    "character_id": "", 
    "title": "Sword Aliamah1",
    "description": "Best sword"
}

### 

@item_id = fdfd9baa-bf45-11f0-b998-0250edc111c5

GET {{BaseApiUrl}}/world/{{world_id}}/artifact/{{item_id}}

### World Update

GET {{BaseApiUrl}}/world/{{world_id}}/artifact/{{item_id}}/edit
Authorization: Bearer {{token}}

PATCH {{BaseApiUrl}}/world/{{world_id}}/artifact/{{item_id}}
Content-Type: application/json

{
    "character_id": "",
    "title": "Sword Aliamah",
    "description": "Best sword in Falish Region"
}

### World Delete 

DELETE {{BaseApiUrl}}/world/{{world_id}}/artifact/{{item_id}}